name: Amazon CI/CD test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run TestNG Tests
        run: |
          mkdir -p allure-results
          mvn test -Dallure.results.directory=allure-results -Dtestng.verbose=2

      - name: Debug Allure Results
        run: |
          echo "Contents of allure-results:"
          ls -R allure-results

      - name: Debug Surefire Reports
        run: |
          echo "Contents of Surefire reports:"
          ls -R target/surefire-reports

      - name: Run a Single Test for Debugging
        run: |
          mvn -Dtest=YourTestClass test

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
